worker_processes 4;
worker_rlimit_nofile 65535;

events {
    worker_connections 65535;
    use epoll;
}

http {
    keepalive_timeout 0;
    client_max_body_size 1m;
    access_log off;

    lua_package_path "/usr/local/openresty/site/lualib/?.lua;/usr/local/openresty/lualib/?.lua;/etc/nginx/lua/?.lua;;";

    # Docker internal DNS resolver
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 8080;

        location /health {
            return 200 '{"status":"ok"}';
            add_header Content-Type application/json;
        }

        location / {
            content_by_lua_file /etc/nginx/lua/collect.lua;
        }
    }
}
